### ISSUE TITLE
When opening a new Script Editor window, constrain dimensions to desktop

### ISSUE THREAD

**Issue by acardona** [scijava/script-editor#38]
In VNC sessions, opening a Script Editor larger than the dimensions of the desktop can segfault the JVM 8.0 in a way that it takes down the VNC server too, meaning, the X11 window manager system crashes as well.

One way to avoid this would be to check, when opening a Script Editor window, if the dimensions stored in the preferences are larger than the desktop dimensions, and constrain them not to be. That would be desirable anyway.

**Comment by acardona** [comment]
@ctrueden , where are the preferences stored in the user's home dir? We document here how to remove these preferences so that the Script Editor won't open and crash a VNC session.

**Comment by imagejan** [comment]
Does [this SO answer](https://stackoverflow.com/a/1320798/1919049) about the `Preferences` location help?

**Comment by ctrueden** [comment]
I'd like to avoid explicitly documenting where the preferences are stored, in case the mechanism changes in the future. (There has been talk in the past of reimplementing the `DefaultPrefService` to use some platform-independent YAML-backed thing, maybe with help from `snakeyaml`, instead of leaning on the `java.util.Preferences` API.)

How about documenting how to clear them using code? E.g. `prefService.clearAll()`, or better: `prefService.clear(TheClassWhosePrefsCauseTheBreakage.class)`.

Also: clearing the preferences works around a bug, right? We should fix it so that the Script Editor doesn't crash VNC no matter what its preferences are, no?

**Comment by acardona** [comment]
Thanks @imagejan that was useful, I found the file and removed it.

While I agree with @ctrueden in principle, in practice removing the file is the easier way. It is unclear where the ```prefService``` instance is to be found, or how to invoke it if the Script Editor itself cannot be opened.

**Comment by ctrueden** [comment]
The `prefService` is a private field of `TextEditor`.

**Comment by acardona** [comment]
Incidentally, a fix for this issue is currently here https://github.com/scijava/script-editor/pull/46/commits/7507734c711156b8428ba4c23f06f157301f449c

**Comment by acardona** [comment]
Fixed.
