### ISSUE TITLE
IJ1 macro, parameter annotation. "Statement cannot begin with '#' in line 3."

### ISSUE THREAD

**Issue by cmci** [scijava/script-editor#7]
Running the following code with IJ1 as selected language 

```
# @File myFile

 print(myFile) 
```

does pop-up a window to select a file but after "ok", the editor returns an error like below. 

> Statement cannot begin with '#' in line 3.
> <#> @ File myFile

**Comment by ctrueden** [comment]
The ImageJ 1.x macro language uses `//` for its comments. At the moment, the `@` parameters are not stripped from the script before execution, which is why they need to be commented out. Try this:
```javascript
// @File myFile

print(myFile)
```

At the NEUBIAS conference, @imagejan and I discussed stripping out these parameters before execution, so that scripts can look cleaner without the leading comments. There are a couple of pieces of work to be done to make this possible, though. In particular, I'd like to have the Script Editor do proper syntax highlighting of the `@` parameters regardless of the selected language, which will be doable, but a little tricky.

**Comment by cmci** [comment]
Thanks @ctrueden ! Sounds obvious using double slash. I kind of brainlessly took example from 

https://imagej.net/Script_Parameters#Files_and_Folders

This example code is with which language? I will edit the wiki to add that information.

**Comment by ctrueden** [comment]
> This example code is with which language? I will edit the wiki to add that information.

Python!

**Comment by cmci** [comment]
again, I now remembered `print` also works with parenthesis in python... thanks
